@startuml

actor application_administrator

application_administrator ->> NesterovichAleksandr.OnlineReservedTickets.service.Application : createCinema()
activate application_administrator
application_administrator ->> NesterovichAleksandr.OnlineReservedTickets.service.Application : fillInfoCinema()
application_administrator ->> NesterovichAleksandr.OnlineReservedTickets.service.Application : saveCinema()
deactivate application_administrator

activate NesterovichAleksandr.OnlineReservedTickets.service.Application
create NesterovichAleksandr.OnlineReservedTickets.service.Cinema
NesterovichAleksandr.OnlineReservedTickets.service.Application -->> NesterovichAleksandr.OnlineReservedTickets.service.Cinema
NesterovichAleksandr.OnlineReservedTickets.service.Application -> NesterovichAleksandr.OnlineReservedTickets.service.Cinema : fillInfoCinema(name,address)
activate NesterovichAleksandr.OnlineReservedTickets.service.Cinema
NesterovichAleksandr.OnlineReservedTickets.service.Application <<-- NesterovichAleksandr.OnlineReservedTickets.service.Cinema
deactivate NesterovichAleksandr.OnlineReservedTickets.service.Cinema
destroy NesterovichAleksandr.OnlineReservedTickets.service.Cinema

database DB

NesterovichAleksandr.OnlineReservedTickets.service.Application -> DB : saveCinema(NesterovichAleksandr.OnlineReservedTickets.service.Cinema)
activate DB
NesterovichAleksandr.OnlineReservedTickets.service.Application <<-- DB
deactivate DB

deactivate NesterovichAleksandr.OnlineReservedTickets.service.Application

@enduml