@startuml

actor application_administrator

application_administrator ->> NesterovichAleksandr.OnlineReservedTickets.service.Application : createFilm()
activate application_administrator
application_administrator ->> NesterovichAleksandr.OnlineReservedTickets.service.Application : fillInfoFilm()
application_administrator ->> NesterovichAleksandr.OnlineReservedTickets.service.Application : saveFilm()
deactivate application_administrator

activate NesterovichAleksandr.OnlineReservedTickets.service.Application
create NesterovichAleksandr.OnlineReservedTickets.service.Film
NesterovichAleksandr.OnlineReservedTickets.service.Application -->> NesterovichAleksandr.OnlineReservedTickets.service.Film
NesterovichAleksandr.OnlineReservedTickets.service.Application -> NesterovichAleksandr.OnlineReservedTickets.service.Film : fillInfoCinema(name,genre, country, duration, year)
activate NesterovichAleksandr.OnlineReservedTickets.service.Film
NesterovichAleksandr.OnlineReservedTickets.service.Application <<-- NesterovichAleksandr.OnlineReservedTickets.service.Film
deactivate NesterovichAleksandr.OnlineReservedTickets.service.Film
destroy NesterovichAleksandr.OnlineReservedTickets.service.Film

database DB

NesterovichAleksandr.OnlineReservedTickets.service.Application -> DB : saveFilm(NesterovichAleksandr.OnlineReservedTickets.service.Film)
activate DB
NesterovichAleksandr.OnlineReservedTickets.service.Application <<-- DB
deactivate DB

deactivate NesterovichAleksandr.OnlineReservedTickets.service.Application

@enduml