@startuml

actor theater_manager

theater_manager ->> NesterovichAleksandr.OnlineReservedTickets.service.Application : createSeance()
activate theater_manager
theater_manager ->> NesterovichAleksandr.OnlineReservedTickets.service.Application : fillInfoSeance()
theater_manager ->> NesterovichAleksandr.OnlineReservedTickets.service.Application : saveSeance()
deactivate theater_manager

activate NesterovichAleksandr.OnlineReservedTickets.service.Application
create NesterovichAleksandr.OnlineReservedTickets.service.Seance
NesterovichAleksandr.OnlineReservedTickets.service.Application -->> NesterovichAleksandr.OnlineReservedTickets.service.Seance
NesterovichAleksandr.OnlineReservedTickets.service.Application -> NesterovichAleksandr.OnlineReservedTickets.service.Seance : fillInfoSeance(data, time)
activate NesterovichAleksandr.OnlineReservedTickets.service.Seance
NesterovichAleksandr.OnlineReservedTickets.service.Application <<-- NesterovichAleksandr.OnlineReservedTickets.service.Seance
deactivate NesterovichAleksandr.OnlineReservedTickets.service.Seance
destroy NesterovichAleksandr.OnlineReservedTickets.service.Seance

database DB

NesterovichAleksandr.OnlineReservedTickets.service.Application -> DB : saveSeance()
activate DB
NesterovichAleksandr.OnlineReservedTickets.service.Application <<-- DB
deactivate DB

deactivate NesterovichAleksandr.OnlineReservedTickets.service.Application

@enduml