@startuml

actor Viewer

Viewer ->> NesterovichAleksandr.OnlineReservedTickets.service.Application : getListReservedTicket()
activate Viewer
activate NesterovichAleksandr.OnlineReservedTickets.service.Application
NesterovichAleksandr.OnlineReservedTickets.service.Application -> DB : getListReservedTicket()
activate DB
NesterovichAleksandr.OnlineReservedTickets.service.Application <<-- DB : ListReservedTicket
deactivate DB
deactivate NesterovichAleksandr.OnlineReservedTickets.service.Application
Viewer ->> NesterovichAleksandr.OnlineReservedTickets.service.Application : deleteReservedTicket()
deactivate Viewer
activate NesterovichAleksandr.OnlineReservedTickets.service.Application
NesterovichAleksandr.OnlineReservedTickets.service.Application -> DB : deleteReservedTicket(Ticket)
activate DB
NesterovichAleksandr.OnlineReservedTickets.service.Application <<-- DB : delete
deactivate DB

database DB

deactivate NesterovichAleksandr.OnlineReservedTickets.service.Application

@enduml