@startuml

actor Viewer

Viewer ->> NesterovichAleksandr.OnlineReservedTickets.service.Application : getInfoViewer()
activate Viewer
activate NesterovichAleksandr.OnlineReservedTickets.service.Application
NesterovichAleksandr.OnlineReservedTickets.service.Application -> DB : getInfoViewer()
activate DB
NesterovichAleksandr.OnlineReservedTickets.service.Application <<-- DB : InfoViewer
deactivate DB
Viewer ->> NesterovichAleksandr.OnlineReservedTickets.service.Application : updateInfoViewer()
Viewer ->> NesterovichAleksandr.OnlineReservedTickets.service.Application : saveInfoViewer()
deactivate Viewer

create InfoViewer
NesterovichAleksandr.OnlineReservedTickets.service.Application -->> InfoViewer


database DB

NesterovichAleksandr.OnlineReservedTickets.service.Application -> DB : updateInfoViewer()
activate DB
NesterovichAleksandr.OnlineReservedTickets.service.Application <<-- DB
deactivate DB

deactivate NesterovichAleksandr.OnlineReservedTickets.service.Application

@enduml