@startuml

actor Viewer

Viewer ->> NesterovichAleksandr.OnlineReservedTickets.service.Application : getListFilm()
activate Viewer
activate NesterovichAleksandr.OnlineReservedTickets.service.Application
NesterovichAleksandr.OnlineReservedTickets.service.Application -> DB : getListFilm()
activate DB
NesterovichAleksandr.OnlineReservedTickets.service.Application <<-- DB : ListFilm
deactivate DB
Viewer ->> NesterovichAleksandr.OnlineReservedTickets.service.Application : getInfoFilm()
Viewer ->> NesterovichAleksandr.OnlineReservedTickets.service.Application : getListSeance()
NesterovichAleksandr.OnlineReservedTickets.service.Application -> DB : getListSeance()()
activate DB
NesterovichAleksandr.OnlineReservedTickets.service.Application <<-- DB : ListSeance
deactivate DB
Viewer ->> NesterovichAleksandr.OnlineReservedTickets.service.Application : getInfoSeance()
Viewer ->> NesterovichAleksandr.OnlineReservedTickets.service.Application : getInfoSeat()
Viewer ->> NesterovichAleksandr.OnlineReservedTickets.service.Application : createReservation()
deactivate Viewer


create NesterovichAleksandr.OnlineReservedTickets.service.ReservedTicket
NesterovichAleksandr.OnlineReservedTickets.service.Application -->> NesterovichAleksandr.OnlineReservedTickets.service.ReservedTicket : create(seance, seat)
NesterovichAleksandr.OnlineReservedTickets.service.Application -> NesterovichAleksandr.OnlineReservedTickets.service.ReservedTicket : getCodeReservation()
activate NesterovichAleksandr.OnlineReservedTickets.service.ReservedTicket
NesterovichAleksandr.OnlineReservedTickets.service.Application <-- NesterovichAleksandr.OnlineReservedTickets.service.ReservedTicket : codeReservation
deactivate NesterovichAleksandr.OnlineReservedTickets.service.ReservedTicket
destroy NesterovichAleksandr.OnlineReservedTickets.service.ReservedTicket



database DB

NesterovichAleksandr.OnlineReservedTickets.service.Application -> DB : saveReservation()
activate DB
NesterovichAleksandr.OnlineReservedTickets.service.Application <<-- DB : reservation
deactivate DB

deactivate NesterovichAleksandr.OnlineReservedTickets.service.Application

@enduml