@startuml

actor guest

guest ->> Application : getListCinema()

activate Application

database DB

Application -> DB : getListCinema()
activate DB
Application <<-- DB : ListCinema
deactivate DB

deactivate Application

@enduml