@startuml

actor guest

guest ->> NesterovichAleksandr.OnlineReservedTickets.service.Application : getListFilm()

activate NesterovichAleksandr.OnlineReservedTickets.service.Application

database DB

NesterovichAleksandr.OnlineReservedTickets.service.Application -> DB : getListFilm()
activate DB
NesterovichAleksandr.OnlineReservedTickets.service.Application <<-- DB : ListFilm
deactivate DB

deactivate NesterovichAleksandr.OnlineReservedTickets.service.Application

@enduml