@startuml

actor theater_manager

theater_manager ->> NesterovichAleksandr.OnlineReservedTickets.service.Application : getListReservedTicket()

activate NesterovichAleksandr.OnlineReservedTickets.service.Application

database DB

NesterovichAleksandr.OnlineReservedTickets.service.Application -> DB : getListReservedTicket()
activate DB
NesterovichAleksandr.OnlineReservedTickets.service.Application <<-- DB : ListReservedTicket
deactivate DB

deactivate NesterovichAleksandr.OnlineReservedTickets.service.Application

@enduml