@startuml

actor guest

guest ->> NesterovichAleksandr.OnlineReservedTickets.service.Application : getListCinema()

activate NesterovichAleksandr.OnlineReservedTickets.service.Application

database DB

NesterovichAleksandr.OnlineReservedTickets.service.Application -> DB : getListCinema()
activate DB
NesterovichAleksandr.OnlineReservedTickets.service.Application <<-- DB : ListCinema
deactivate DB

deactivate NesterovichAleksandr.OnlineReservedTickets.service.Application

@enduml