@startuml

actor guest

guest ->> Application : getListFilm()

activate Application

database DB

Application -> DB : getListFilm()
activate DB
Application <<-- DB : ListFilm
deactivate DB

deactivate Application

@enduml