@startuml

actor guest

guest ->> Application : getListSeance()

activate Application

database DB

Application -> DB : getListSeance()
activate DB
Application <<-- DB : ListSeance
deactivate DB

deactivate Application

@enduml