@startuml

actor guest

guest ->> NesterovichAleksandr.OnlineReservedTickets.service.Application : getListSeance()

activate NesterovichAleksandr.OnlineReservedTickets.service.Application

database DB

NesterovichAleksandr.OnlineReservedTickets.service.Application -> DB : getListSeance()
activate DB
NesterovichAleksandr.OnlineReservedTickets.service.Application <<-- DB : ListSeance
deactivate DB

deactivate NesterovichAleksandr.OnlineReservedTickets.service.Application

@enduml