@startuml

actor viewer

viewer ->> NesterovichAleksandr.OnlineReservedTickets.service.Application : getInfoViewer()

activate NesterovichAleksandr.OnlineReservedTickets.service.Application

database DB

NesterovichAleksandr.OnlineReservedTickets.service.Application -> DB : getInfoViewer()
activate DB
NesterovichAleksandr.OnlineReservedTickets.service.Application <<-- DB : InfoViewer
deactivate DB

deactivate NesterovichAleksandr.OnlineReservedTickets.service.Application

@enduml