@startuml

actor viewer

viewer ->> Application : getInfoViewer()

activate Application

database DB

Application -> DB : getInfoViewer()
activate DB
Application <<-- DB : InfoViewer
deactivate DB

deactivate Application

@enduml